### ISSUE TITLE
[Website] Allow server owner to supply blurayguids and farc to pull GUID level icons from.

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#374]
Currently level icons only display if they're user-generated (hashed) as the server has nowhere to pull icons that are referenced by GUID from.

**Comment by jvyden** [comment]
Hi,

Unfortunately we cannot do this for multiple reasons:

- Legal reasons; distributing proprietary LBP assets of any kind for any reason is a no-go.
- This would almost certainly screw with Vita levels, since Vita has a different set of GUIDs
- Storing the .farc and map on our servers would be very inconvenient, not to mention legal concerns again.

**Comment by TorutheRedFox** [comment]
adding a placeholder icon for such levels rather than leaving them as broken links would be good though
