### ISSUE TITLE
Include CSS in the repository

### ISSUE THREAD

**Issue by TorutheRedFox** [LBPUnion/ProjectLighthouse#449]
The build currently doesn't include the necessary CSS for the website making you have to source it yourself.

**Comment by m88youngling** [comment]
I have actually thought about this a bit, how much of the styling of the website *should* Lighthouse be bundled with? It's possible that instances could build their own custom closed source website and then use Lighthouse api as the base from which to operate the website from. But, for instances without a need for a fancy website, it may not be necessary for stock Lighthouse to come with a super advanced website with advanced CSS styling. However, I think you're right that basic CSS styling may be helpful.

**Comment by Zaprit** [comment]
> I have actually thought about this a bit, how much of the styling of the website _should_ Lighthouse be bundled with? It's possible that instances could build their own custom closed source website and then use Lighthouse api as the base from which to operate the website from. But, for instances without a need for a fancy website, it may not be necessary for stock Lighthouse to come with a super advanced website with advanced CSS styling. However, I think you're right that basic CSS styling may be helpful.

from looking at and testing the code, it's a case of the actual base styles of the page have been replaced with local references to a file to be hosted by lighthouse rather than a reference to a CDN, I'm not sure why this was done but I'm sure there was a good reason for it. on a side note, the logo appears to be missing, even with the CSS put back.
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/18514680/186023365-01b2c7f6-6d66-405c-a271-47af7b62bc18.png">

**Comment by Zaprit** [comment]
Upon further investigation the files are there, the StaticFile parts are not working, at least on my local instance

**Comment by TorutheRedFox** [comment]
the logo is missing because it's two png files

**Comment by TorutheRedFox** [comment]
what should be included is example versions of semantic.min.css, styles.css, and the slot background and overlay images

**Comment by Slendy** [comment]
This is a configuration issue rather than a Project Lighthouse issue. Closing.
