### ISSUE TITLE
LBP will show levels that aren’t compatible for the game

### ISSUE THREAD

**Issue by W0lf4llo** [LBPUnion/ProjectLighthouse#467]
**Describe the bug**
In LBP1 it will show all levels published on the servers instead of levels compatible for the game. This issue persists in LBP1, LBP2, LBP3, and LBP Vita

**To Reproduce**
1. Open any LBP
2. Click on the community tab 
3. Look at the published levels.
4. It will show every published level instead of ones that are compatible 

**Expected behavior**
The game will show every level that is compatible for the game and will show the compatible levels for the “published levels” count for the game.

**Screenshots**
![434835E0-3D9B-4C67-8FAB-5A5C58CA04AE](https://user-images.githubusercontent.com/96880844/187817988-a7a2d4c8-ea28-404d-80b7-af9b1edd87f9.jpeg)
![9048EA06-6B59-45AC-AC5C-5D7A4DE260E0](https://user-images.githubusercontent.com/96880844/187817989-ae65b09c-4a76-4efb-ba97-aadf02cc9b3d.jpeg)

**Game(s) affected**
 - Platform Every platform
 - Game Every game

**Additional context**

**Comment by Arcadius2006** [comment]
iirc it was like this on the official servers too

i have no clue if it actually was like that though

**Comment by jonathan-rosa** [comment]
> iirc it was like this on the official servers too
> 
> i have no clue if it actually was like that though

It was.

Luckily, LBP includes the game version in User-Agent:

- LBP1: `MM CHTTPClient $Id: HTTPClient.cpp 37276 2010-01-15 19:51:36Z amy $`

- LBP2/LBP Vita/LBP HUB/LBP3(0–1.26) include the app version: `MM CHTTPClient LBP2 1.26`

- LBP3 1.27+: `MM CHTTPClient LBP3 1.28`

**You could potentially have some kind of hash table User-Agent->enum mapping in the database for levels/resources, and decide to filter levels/resources that way.** I wouldn't try this for LBP1 though since revision checks branch off when it's a disc/digital copy (don't attempt with LBP1.)
