### ISSUE TITLE
Custom Word Filter

### ISSUE THREAD

**Issue by m88youngling** [LBPUnion/ProjectLighthouse#535]
@Slendy mentioned to me that a word filter can be enabled with Lighthouse but all the words are hardcoded. It'd be very handy to have a customizable word filter. You could add words to a comma separated list either in the lighthouse.yml config or you could customize the word filter via the admin panel.

- [ ] Filter level titles
- [ ] Filter comments
- [ ] Filter reviews
- [ ] Filter user profiles

**Comment by Zaprit** [comment]
currently it's [here](https://github.com/LBPUnion/ProjectLighthouse/blob/main/ProjectLighthouse/chatCensoredList.txt)

**Comment by m88youngling** [comment]
> currently it's [here](https://github.com/LBPUnion/ProjectLighthouse/blob/main/ProjectLighthouse/chatCensoredList.txt)

Can instance owners easily edit the list on their server, or will it auto update when they update to latest changes from the repo?

**Comment by Zaprit** [comment]
it will likely be clobbered when the server gets updated

**Comment by m88youngling** [comment]
Crap 💀 how do we deal with that?

**Comment by Zaprit** [comment]
give me an hour

**Comment by m88youngling** [comment]
I have the 'furry' mode activated on Beacon and it doesn't seem to moderate level titles

**Comment by m88youngling** [comment]
Seems that comments don't get filtered either, I bet that only in-game text chat and magic mouths get filtered at the moment

**Comment by Ezoiar** [comment]
To avoid language collisions, I suggest using the selected/preferred language as well to select a specific group of word filter.
For example, using fantasy made up languages lol: Frunkish: Ung ba moda (Fu*k you man) Mongtsh: Ung ta te moda (How is your day?). Right now looking at the report at #bug-blasters from October 29th, I assume right now it goes like this.

Ung ba moda - gets censored because it means something bad
Ung ta te moda - gets censored anyways despite not being bad.

With the solution I suggested, It goes like this:

User with Frunkish set as preferred language:

Ung ba moda (gets censored)
Ung ta te moda (gets censored)

User with Mongtsh set as preferred language:

Ung ba moda (does not get censored)
Ung ta te moda (does not get censored)

This solution to a problem does bring both good and potential bad.
The goods: Brings more freedom to foreign-speaking users and community, Does not censor any word in foreign languages.
The bad, there's only one: If the user does abuse the solution by speaking English despite being on foreign language, Only the host/other players can report it via good grief, This could be a violation for circumventing the word filter.

It can be considered as a seperate issue but I thought would be best here for now.

**Comment by Zaprit** [comment]
> give me an hour
> 
> I fix 🙂

my ability to judge complexity is not good

**Comment by m88youngling** [comment]
💀

**Comment by Cryptofowl** [comment]
You could try adding a .gitattributes file with a merge strategy that ignores the non-local word filter file. I'll get a PR up for this in a sec so you can see what I mean

**Comment by Cryptofowl** [comment]
Whoops, no write access (duh) but you can just save a .gitattributes file with
`chatCensoredList.txt merge=ours`

That should prevent merged updates from overwriting custom word filter lists and solve the issue.

**Comment by m88youngling** [comment]
I've edited this issue to include a checklist of stuff the word filter does not yet cover.

**Comment by m88youngling** [comment]
I edited this again to include user profiles

**Comment by Slendy** [comment]
Closing as this has been implemented in #603
