### ISSUE TITLE
Seperate LBP Vita and LBP2/3 earth decorations

### ISSUE THREAD

**Issue by turecross321** [LBPUnion/ProjectLighthouse#66]
Since LBP Vita cannot load LBP2 and LBP3 earth decorations and vice versa, users should have a separate Vita earth and a seperate main earth. This would be nice for cross integration between Vita and Main.

**Comment by FridiNaTor1** [comment]
I don't think this has any use. Since LBP Vita uses a different digest key. And it's much easier to just have a seperate server instance for Vita. I would say that PS3, PSP and PS Vita versions of the games all need their seperate instance of the server.

Please correct me if I am wrong in anyway. Otherwise the idea is very bright :)

**Comment by jvyden** [comment]
While you need to run separate instances right now, the plan is ultimately to tie all 3 platforms together. UnionPatcher will be able to patch the digest key in the near future.
