### ISSUE TITLE
scores set by name changed users all deleted

### ISSUE THREAD

**Issue by diediediebitch** [LBPUnion/ProjectLighthouse#881]
Any psn user that changed their name at some point had all of their scores set before they changed their names randomly deleted.

before
![image](https://github.com/LBPUnion/ProjectLighthouse/assets/137153247/3415a8c4-7a26-419e-b3ac-5aae599ba98f)

after
![image](https://github.com/LBPUnion/ProjectLighthouse/assets/137153247/be48caff-3de1-495d-9146-a63b8dd9da3c)

DemarLowry_ changed his name to WooplusUser and had all his scores set before his name change removed

**Comment by Slendy** [comment]
This was due to the old system not tracking by user IDs and only tracking usernames. A recent change in how scores work behind the scenes meant that all scores with usernames that no longer existed were deleted. Unfortunately, this was an unavoidable problem due to how scores worked previously and Lighthouse not tracking username history. With the new system, scores will be tracked across name changes. All we can do now is manually restore scores from users who changed their names.

**Comment by sudokoko** [comment]
I've gone ahead and notified the affected users on the Beacon side of things.

**Comment by W0lf4llo** [comment]
Should we close this issue since it can’t really be fixed

**Comment by sudokoko** [comment]
Stale issue, mitigation efforts continue
